# Generated by Django 6.1.1 on 2026-10-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
