# Generated by Django 6.1.1 on 2026-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desired_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment',
            field=models.CharField(choices=[('any', 'Любая'), ('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('project', 'Проектная работа'), ('internship', 'Стажировка')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(choices=[('any', 'Любой'), ('no_experience', 'Без опыта'), ('1_3', '1–3 года'), ('3_6', '3–6 лет'), ('6_plus', '6+ лет')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wishes',
            field=models.TextField(blank=True, help_text='Дополнительные пожелания к вакансии'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_format',
            field=models.CharField(choices=[('any', 'Любой'), ('remote', 'Удалённая работа'), ('office', 'Офис'), ('hybrid', 'Гибрид')], default='any', max_length=20),
        ),
    ]
